name: template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  common:
    path: ../common
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  domain:
    path: ../domain
  envied: ^0.5.3
  firebase_core: ^2.27.2
  firebase_messaging: ^14.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavorizr: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  go_router: ^13.0.1
  injectable: ^2.3.2
  isar_flutter_libs: ^3.1.0+1
  notification_permissions: ^0.6.1
  path_provider: ^2.1.2
  pull_to_refresh: ^2.0.0
  shared:
    path: ../shared
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  web: ^0.5.1

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  golden_toolkit: ^0.15.0
  hodoan_lint: ^0.0.2
  injectable_generator: ^2.4.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.2
flutter:
  generate: true
  uses-material-design: true

# flutter pub run flutter_flavorizr
flavorizr:
  flavors:
    dev:
      app:
        name: "Template Dev"

      android:
        applicationId: "com.hodoan.template.dev"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "com.hodoan.template.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"
    ctest:
      app:
        name: "Template Dev"

      android:
        applicationId: "com.hodoan.template.dev"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "com.hodoan.template.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"
    stg:
      app:
        name: "Template Staging"

      android:
        applicationId: "com.hodoan.template.staging"
        firebase:
          config: ".firebase/stg/google-services.json"

      ios:
        bundleId: "com.hodoan.template.staging"
        firebase:
          config: ".firebase/stg/GoogleService-Info.plist"

    prod:
      app:
        name: "Template"

      android:
        applicationId: "com.hodoan.template"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "com.hodoan.template"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"