name: template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  dartz: ^0.10.1
  dio: ^5.4.0
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavorizr: ^2.2.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.6
  go_router: ^13.0.1
  injectable: ^2.3.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  bdd_widget_test: ^1.4.0
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  freezed: ^2.4.6
  golden_toolkit: ^0.15.0
  hodoan_lint: ^0.0.2
  injectable_generator: ^2.4.1
  integration_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.2
  retrofit_generator: ^8.0.6
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
