name: template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  common:
    path: ../common
  cupertino_icons: ^1.0.2
  domain:
    path: ../domain
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavorizr: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  go_router: ^13.0.1
  injectable: ^2.3.2
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  dartz: ^0.10.1
  envied_generator: ^0.5.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  golden_toolkit: ^0.15.0
  hodoan_lint: ^0.0.2
  injectable_generator: ^2.4.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.2
flutter:
  generate: true
  uses-material-design: true