name: core_generator
description: "Core generator build all future clean architecture"
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  change_case: ^2.0.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  json_annotation: ^4.8.1
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  hodoan_lint: ^0.0.4
  json_serializable: ^6.7.1
  lints: ^3.0.0
