name: figma_gen_core
description: "Generated properties figma file"
version: 0.0.2
homepage: 'https://github.com/ho-doan/base_s'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  dart_style: ^2.3.6
  dio: ^5.4.1
  json_annotation: ^4.8.1
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0
