name: domain
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  copy_with_extension: ^5.0.4
  dartz: ^0.10.1
  dio: ^5.4.0
  envied: ^0.5.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  injectable: ^2.3.2
  isar: ^3.1.0+1
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.8
  copy_with_extension_gen: ^5.0.4
  envied_generator: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hodoan_lint: ^0.0.2
  injectable_generator: ^2.4.1
  isar_generator:
    git:
      url: https://github.com/ndelanou/isar.git
      path: packages/isar_generator
      ref: analyzer-v6
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.2
  retrofit_generator: ^8.0.6

flutter:
  generate: true
