name: common
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.4.0
flutter:
  generate: true
  assets:
    - assets/icons/
  fonts:
    - family: IconCustoms
      fonts:
        - asset: assets/fonts/IconCustoms.ttf
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro.ttf
flutter_gen:
  output: lib/generator
  line_length: 80
  colors:
    inputs:
      - assets/color/colors.xml
  fonts:
    enabled: true
    outputs:
      package_parameter_enabled: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  integrations:
    flutter_svg: true