name: common
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.4.0
flutter:
  generate: true
  assets:
    - assets/icons/
flutter_gen:
  output: lib/generator
  line_length: 80
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  integrations:
    flutter_svg: true