name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hodoan_lint: ^0.0.2

flutter:
  assets:
    - .env
    - .env.dev
    - .env.stg
    - .env.test
