name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  envied: ^0.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hodoan_lint: ^0.0.2
flutter:
  # generate: true
