name: core_clean_gen
description: "Generated core clean"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

executables:
  core_gen: core_clean_gen

dependencies:
  args: ^2.4.2
  # core_generator: ^0.0.3
  core_generator: 
    path: ../core_generator

dev_dependencies:
  hodoan_lint: ^0.0.4
  lints: ^3.0.0
  test: ^1.25.2
  test_process: ^2.1.0

  # figma_gen_core:
  #   path: ../core
