name: figma_gen
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

executables: 
  figmagen: figma_gen_command

dependencies:
  args: ^2.4.2
  core:
    path: ../core

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  test_process: ^2.1.0