name: figma_gen_hd
description: "Generated properties figma file"
version: 0.0.3
homepage: "https://github.com/ho-doan/base_s"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

executables:
  figmagen: figma_gen_command

dependencies:
  args: ^2.4.2
  figma_gen_core: ^0.0.3
  # figma_gen_core: 
  #   path: ../command

dev_dependencies:
  hodoan_lint: ^0.0.4
  lints: ^3.0.0
  test: ^1.25.2
  test_process: ^2.1.0

  # figma_gen_core:
  #   path: ../core
