// Mocks generated by Mockito 5.4.4 from annotations
// in template/test/golden/home/home_golden_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:domain/domain.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryUseCase extends _i1.Mock implements _i3.CategoryUseCase {
  @override
  _i4.Future<_i2.Either<_i3.ErrorState<dynamic>, List<_i3.CategoryModel>>>
      fetch({
    bool? forceRefresh = false,
    _i5.RootIsolateToken? token,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #fetch,
              [],
              {
                #forceRefresh: forceRefresh,
                #token: token,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i3.ErrorState<dynamic>,
                        List<_i3.CategoryModel>>>.value(
                _FakeEither_0<_i3.ErrorState<dynamic>, List<_i3.CategoryModel>>(
              this,
              Invocation.method(
                #fetch,
                [],
                {
                  #forceRefresh: forceRefresh,
                  #token: token,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i3.ErrorState<dynamic>,
                        List<_i3.CategoryModel>>>.value(
                _FakeEither_0<_i3.ErrorState<dynamic>, List<_i3.CategoryModel>>(
              this,
              Invocation.method(
                #fetch,
                [],
                {
                  #forceRefresh: forceRefresh,
                  #token: token,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i3.ErrorState<dynamic>, List<_i3.CategoryModel>>>);
}

/// A class which mocks [ProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductUseCase extends _i1.Mock implements _i3.ProductUseCase {
  @override
  _i4.Future<_i2.Either<_i3.ErrorState<dynamic>, List<_i3.ProductModel>>> fetch(
    int? categoryId, {
    bool? forceRefresh = false,
    _i5.RootIsolateToken? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [categoryId],
          {
            #forceRefresh: forceRefresh,
            #token: token,
          },
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i3.ErrorState<dynamic>, List<_i3.ProductModel>>>.value(
            _FakeEither_0<_i3.ErrorState<dynamic>, List<_i3.ProductModel>>(
          this,
          Invocation.method(
            #fetch,
            [categoryId],
            {
              #forceRefresh: forceRefresh,
              #token: token,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2
                .Either<_i3.ErrorState<dynamic>, List<_i3.ProductModel>>>.value(
            _FakeEither_0<_i3.ErrorState<dynamic>, List<_i3.ProductModel>>(
          this,
          Invocation.method(
            #fetch,
            [categoryId],
            {
              #forceRefresh: forceRefresh,
              #token: token,
            },
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i3.ErrorState<dynamic>, List<_i3.ProductModel>>>);
}
